version: "3.8"

services:
  etl:
    build: .
    container_name: etl_pipeline
    volumes:
      - .:/app
    environment:
      - PREFECT_API_URL=http://host.docker.internal:4200/api
    command: ["python", "project_solution.py"]